// <auto-generated />
namespace Vialidad.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class V05_Referencia_Fixs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V05_Referencia_Fixs));
        
        string IMigrationMetadata.Id
        {
            get { return "201812071940550_V05_Referencia_Fixs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
